package io.github.depermitto.bullettrain.theme.palettes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF00503D)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF1F775E)
private val onPrimaryContainerLight = Color(0xFFFFFFFF)
private val secondaryLight = Color(0xFF476459)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFCDEEDF)
private val onSecondaryContainerLight = Color(0xFF335045)
private val tertiaryLight = Color(0xFF473D78)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF6B619F)
private val onTertiaryContainerLight = Color(0xFFFFFFFF)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFF7FAF6)
private val onBackgroundLight = Color(0xFF181D1A)
private val surfaceLight = Color(0xFFF7FAF6)
private val onSurfaceLight = Color(0xFF181D1A)
private val surfaceVariantLight = Color(0xFFDAE5DE)
private val onSurfaceVariantLight = Color(0xFF3F4944)
private val outlineLight = Color(0xFF6F7A74)
private val outlineVariantLight = Color(0xFFBEC9C3)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2D312F)
private val inverseOnSurfaceLight = Color(0xFFEEF2EE)
private val inversePrimaryLight = Color(0xFF85D6B8)
private val surfaceDimLight = Color(0xFFD7DBD7)
private val surfaceBrightLight = Color(0xFFF7FAF6)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF1F4F1)
private val surfaceContainerLight = Color(0xFFEBEFEB)
private val surfaceContainerHighLight = Color(0xFFE5E9E5)
private val surfaceContainerHighestLight = Color(0xFFE0E3E0)

private val primaryDark = Color(0xFF85D6B8)
private val onPrimaryDark = Color(0xFF00382A)
private val primaryContainerDark = Color(0xFF005C46)
private val onPrimaryContainerDark = Color(0xFFB9FFE3)
private val secondaryDark = Color(0xFFADCEBF)
private val onSecondaryDark = Color(0xFF19362C)
private val secondaryContainerDark = Color(0xFF28453A)
private val onSecondaryContainerDark = Color(0xFFBBDBCD)
private val tertiaryDark = Color(0xFFCABEFF)
private val onTertiaryDark = Color(0xFF312762)
private val tertiaryContainerDark = Color(0xFF524884)
private val onTertiaryContainerDark = Color(0xFFF4EEFF)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF101412)
private val onBackgroundDark = Color(0xFFE0E3E0)
private val surfaceDark = Color(0xFF101412)
private val onSurfaceDark = Color(0xFFE0E3E0)
private val surfaceVariantDark = Color(0xFF3F4944)
private val onSurfaceVariantDark = Color(0xFFBEC9C3)
private val outlineDark = Color(0xFF88938D)
private val outlineVariantDark = Color(0xFF3F4944)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE0E3E0)
private val inverseOnSurfaceDark = Color(0xFF2D312F)
private val inversePrimaryDark = Color(0xFF0A6B53)
private val surfaceDimDark = Color(0xFF101412)
private val surfaceBrightDark = Color(0xFF363A38)
private val surfaceContainerLowestDark = Color(0xFF0B0F0D)
private val surfaceContainerLowDark = Color(0xFF181D1A)
private val surfaceContainerDark = Color(0xFF1C211E)
private val surfaceContainerHighDark = Color(0xFF272B29)
private val surfaceContainerHighestDark = Color(0xFF313633)

val EmeraldPalette = Palette(
    name = "Emerald",
    lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    ), darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
)
