package io.github.depermitto.bullettrain.theme.palettes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF655C5B)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFC9BEBC)
private val onPrimaryContainerLight = Color(0xFF37302F)
private val secondaryLight = Color(0xFF250001)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFF5B1011)
private val onSecondaryContainerLight = Color(0xFFFFA19A)
private val tertiaryLight = Color(0xFF000000)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF272528)
private val onTertiaryContainerLight = Color(0xFFB5AFB4)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFFDF8F7)
private val onBackgroundLight = Color(0xFF1C1B1B)
private val surfaceLight = Color(0xFFFDF8F7)
private val onSurfaceLight = Color(0xFF1C1B1B)
private val surfaceVariantLight = Color(0xFFEEDFDD)
private val onSurfaceVariantLight = Color(0xFF4E4543)
private val outlineLight = Color(0xFF7F7573)
private val outlineVariantLight = Color(0xFFD1C4C1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF323030)
private val inverseOnSurfaceLight = Color(0xFFF5F0EF)
private val inversePrimaryLight = Color(0xFFCFC4C2)
private val surfaceDimLight = Color(0xFFDED9D8)
private val surfaceBrightLight = Color(0xFFFDF8F7)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF7F2F2)
private val surfaceContainerLight = Color(0xFFF2EDEC)
private val surfaceContainerHighLight = Color(0xFFECE7E6)
private val surfaceContainerHighestLight = Color(0xFFE6E1E0)

private val primaryDark = Color(0xFFE4D8D6)
private val onPrimaryDark = Color(0xFF362F2E)
private val primaryContainerDark = Color(0xFFBAAFAD)
private val onPrimaryContainerDark = Color(0xFF2B2523)
private val secondaryDark = Color(0xFFFFB3AD)
private val onSecondaryDark = Color(0xFF601313)
private val secondaryContainerDark = Color(0xFF3C0003)
private val onSecondaryContainerDark = Color(0xFFF5847D)
private val tertiaryDark = Color(0xFFCBC5C9)
private val onTertiaryDark = Color(0xFF322F33)
private val tertiaryContainerDark = Color(0xFF0A080B)
private val onTertiaryContainerDark = Color(0xFF9E999D)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF141313)
private val onBackgroundDark = Color(0xFFE6E1E0)
private val surfaceDark = Color(0xFF141313)
private val onSurfaceDark = Color(0xFFE6E1E0)
private val surfaceVariantDark = Color(0xFF4E4543)
private val onSurfaceVariantDark = Color(0xFFD1C4C1)
private val outlineDark = Color(0xFF9A8E8C)
private val outlineVariantDark = Color(0xFF4E4543)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE6E1E0)
private val inverseOnSurfaceDark = Color(0xFF323030)
private val inversePrimaryDark = Color(0xFF655C5B)
private val surfaceDimDark = Color(0xFF141313)
private val surfaceBrightDark = Color(0xFF3A3938)
private val surfaceContainerLowestDark = Color(0xFF0F0E0E)
private val surfaceContainerLowDark = Color(0xFF1C1B1B)
private val surfaceContainerDark = Color(0xFF211F1F)
private val surfaceContainerHighDark = Color(0xFF2B2A29)
private val surfaceContainerHighestDark = Color(0xFF363434)

val WoodsmokePalette = Palette(
    name = "Woodsmoke",
    lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    ), darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
)
